### ISSUE TITLE
z-offset setting not visible in 'per-object' settings

### ISSUE THREAD

**Issue by imagesurgery** [fieldOfView/ZOffsetPlugin#37]
The ui is not revealing the z-offset setting. It is visible and functional under the normal (global) settings.

Not sure if this is a limitation with Cura, but if not, this would be an absolutely killer feature for my very-large-print-bed levelling procedure. I'm currently manually editing a series of squares and it's very unruly and error prone as the repetitions grow.

(if you're interested, I'm printing a series of squares with z offsets of +/- 0.05mm, at a series of probe points, then manually adjusting the UBL grid based on real-world results. It's working splendidly but is such a pain to manually set up for each grid size, filament, temperature, and a handful of other variables)

**Comment by fieldOfView** [comment]
This is by design. Having different layers heights within one layer could lead to collisions of the nozzle with previously printed parts.
When manually editing gcode, you can make sure that does not happen. This is much trickier in Cura, since you don't have fine control over the print order, and there could be hard to predict (travel) moves.

To make your manual process less error prone, I would recommend writing a script that creates the gcode.
